# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, inputs, ...}: {
	flake.nixosModules.phosHardware = { config, lib, pkgs, modulesPath, ... }: {
	  imports =
	    [ (modulesPath + "/installer/scan/not-detected.nix")
	    ];

	  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
	  boot.initrd.kernelModules = [ ];
	  boot.kernelModules = [ "kvm-amd" ];
	  boot.extraModulePackages = [ ];

	  fileSystems."/" =
	    { device = "/dev/disk/by-uuid/edf9f449-b978-46de-b7ab-25d31f977a4e";
	      fsType = "btrfs";
	    };

	  fileSystems."/home" =
	    { device = "/dev/disk/by-uuid/edf9f449-b978-46de-b7ab-25d31f977a4e";
	      fsType = "btrfs";
	      options = [ "subvol=home" ];
	    };

	  fileSystems."/nix" =
	    { device = "/dev/disk/by-uuid/edf9f449-b978-46de-b7ab-25d31f977a4e";
	      fsType = "btrfs";
	      options = [ "subvol=nix" ];
	    };

	  fileSystems."/boot" =
	    { device = "/dev/disk/by-uuid/9042-CC70";
	      fsType = "vfat";
	      options = [ "fmask=0077" "dmask=0077" ];
	    };

	  swapDevices = [ ];

	  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
